<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.suno</groupId>
        <artifactId>suno-parent</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <artifactId>suno-operations</artifactId>
    <dependencies>
        <dependency>
            <groupId>com.suno</groupId>
            <artifactId>suno-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.suno</groupId>
            <artifactId>suno-identity</artifactId>
        </dependency>
        <dependency>
            <groupId>com.suno</groupId>
            <artifactId>suno-recycle</artifactId>
        </dependency>
        <dependency>
            <groupId>com.suno</groupId>
            <artifactId>suno-marketplace</artifactId>
        </dependency>
        <dependency>
            <groupId>com.suno</groupId>
            <artifactId>suno-payment</artifactId>
        </dependency>
    </dependencies>
</project>
