package com.recycle.mall.interfaces.http;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

abstract class TestAuthSupport {

    protected static final String AUTO_REQUEST_ID_REGEX = ".*requestId=req-[a-f0-9]{32}.*";

    @Autowired
    protected MockMvc mockMvc;
    @Autowired
    protected ObjectMapper objectMapper;

    protected Tokens loginAndGetTokens(String username, String password) throws Exception {
        return loginAndGetTokens(username, password, "web-default");
    }

    protected Tokens loginAndGetTokens(String username, String password, String deviceId) throws Exception {
        String body = "{\"username\":\"" + username + "\",\"password\":\"" + password + "\",\"deviceId\":\"" + deviceId + "\"}";
        MvcResult loginResult = mockMvc.perform(post("/api/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(body))
                .andExpect(status().isOk())
                .andReturn();
        JsonNode root = objectMapper.readTree(loginResult.getResponse().getContentAsString());
        assertTrue(root.get("success").asBoolean());
        JsonNode accessToken = root.get("data").get("accessToken");
        JsonNode refreshToken = root.get("data").get("refreshToken");
        assertNotNull(accessToken);
        assertNotNull(refreshToken);
        return new Tokens(accessToken.asText(), refreshToken.asText());
    }

    protected boolean hasAutoGeneratedRequestId(String detail) {
        return detail != null && detail.matches(AUTO_REQUEST_ID_REGEX);
    }

    protected record Tokens(String accessToken, String refreshToken) {
    }
}
